### PR TITLE
Fixing 2 regressions in 0.9.1

### LINKED ISSUE #121: User Data content should be base64 encoded when passed to aws sdk
When using 0.9.0 and supplying a file to `user_data` the `create` action throws an error:
```
------Exception-------
Class: Kitchen::ActionFailed
Message: Failed to complete #create action: [Invalid BASE64 encoding of user data]
---Nested Exception---
Class: Aws::EC2::Errors::InvalidParameterValue
Message: Invalid BASE64 encoding of user data
```
If the user data file used has base64 encoded content then the create action is successful

The content of the user data file should be base64 encoded when being provided to aws sdk

### LINKED ISSUE #127: [Network interfaces and an instance-level security groups may not be specified on the same request]
I get the warnings, they have meaning, but this error thats killing me does not.  theres nothing in the changelogs or readme as far as I can tell.
```
+ kitchen test
-----> Starting Kitchen (v1.4.0)
$$$$$$ WARN: The driver[Kitchen::Driver::Ec2] config key `ebs_delete_on_termination` is deprecated, please use `block_device_mappings`
$$$$$$ WARN: The driver[Kitchen::Driver::Ec2] config key `ssh_key` is deprecated, please use `transport.ssh_key`
$$$$$$ WARN: The driver[Kitchen::Driver::Ec2] config key `username` is deprecated, please use `transport.username`
$$$$$$ WARN: The driver[Kitchen::Driver::Ec2] config key `flavor_id` is deprecated, please use `instance_type`
$$$$$$ WARN: aws_access_key_id has been deprecated, please use ENV['AWS_ACCESS_KEY_ID'] or ~/.aws/credentials.  See the README for more details
$$$$$$ WARN: aws_secret_access_key has been deprecated, please use ENV['AWS_SECRET_ACCESS_KEY'] or ~/.aws/credentials.  See the README for more details
-----> Cleaning up any prior instances of <default-debian-ec2>
-----> Destroying <default-debian-ec2>...
       Finished destroying <default-debian-ec2> (0m0.00s).
-----> Testing <default-debian-ec2>
-----> Creating <default-debian-ec2>...
       Creating <>...
If you are not using an account that qualifies under the AWS
free-tier, you may be charged to run these suites. The charge
should be minimal, but neither Test Kitchen nor its maintainers
are responsible for your incurred costs.
 
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: Failed to complete #create action: [Network interfaces and an instance-level security groups may not be specified on the same request]
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
Build step 'Execute shell' marked build as failure
ERROR: Publisher jp.skypencil.jenkins.regression.RegressionReportNotifier aborted due to exception
java.lang.NoSuchMethodError: hudson.model.AbstractBuild.getTestResultAction()Lhudson/tasks/test/AbstractTestResultAction;
	at jp.skypencil.jenkins.regression.RegressionReportNotifier.perform(RegressionReportNotifier.java:97)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:761)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:721)
	at hudson.model.Build$BuildExecution.post2(Build.java:183)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:670)
	at hudson.model.Run.execute(Run.java:1775)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:89)
	at hudson.model.Executor.run(Executor.java:240)
[ci-game] evaluating rule: Build result
[ci-game] evaluating rule: Increased number of passed tests
[ci-game] evaluating rule: Decreased number of passed tests
[ci-game] evaluating rule: Increased number of failed tests
[ci-game] evaluating rule: Decreased number of failed tests
[ci-game] evaluating rule: Increased number of skipped tests
[ci-game] evaluating rule: Decreased number of skipped tests
[ci-game] evaluating rule: Changed number of compiler warnings
Warning: you have no plugins providing access control for builds, so falling back to legacy behavior of permitting any downstream builds to be triggered
Notifying upstream projects of job completion
Finished: FAILURE
```

### PR DESCRIPTION
**Pull request by tyler-ball**
Fixes #121 
Fixes #127 

Also setting the network interface to `delete_on_termination` of the instance so there aren't orphan devices hanging around

\cc @fnichol @kplimack @litjoco

### CODE REVIEW

File: lib/kitchen/driver/aws/instance_generator.rb [hunk 1]
```diff
@@ -134,14 +143,15 @@ def debug_if_root_device(bdms)
...
-          unless @user_data
-            if config[:user_data] && File.file?(config[:user_data])
+          return nil if config[:user_data].nil?
+          @user_data ||= begin
+            if File.file?(config[:user_data])
               @user_data = File.read(config[:user_data])
             else
               @user_data = config[:user_data]
             end
+            @user_data = Base64.encode64(@user_data)
```
Comment (fnichol) [inline lib/kitchen/driver/aws/instance_generator.rb]: Interesting, that seems to be a low-level concern that we need to deal with as a user of the sdk. Ah well

**Comment by fnichol** [comment]
Yep, LGTM! :+1:

**Comment by kplimack** [comment]
any idea when this will get merged?

**Comment by kplimack** [comment]
@tyler-ball  Thanks!

**Comment by litjoco** [comment]
Thank you :thumbsup:

**Comment by kplimack** [comment]
I'm having trouble now with the ec2-instance being created and immediately
terminated while TK is waiting for it to become ready. i've created a new
issue for it.  https://github.com/test-kitchen/kitchen-ec2/issues/130
