### PR TITLE
Prefer non-Beta RHEL AMIs in search; remove encoding comments

### LINKED ISSUE #505: platform: rhel-7 search gets a beta ami
## :ghost: Brief Description

When using test-kitchen with ec2 driver I'm trying to get latest stable version of RHEL 7 image automatically. Instead of RHEL 7.8 I'm getting a RHEL 7.9 beta ami.

## Version

Chef Workstation version: 20.7.96
Chef Infra Client version: 16.2.73
Chef InSpec version: 4.21.3
Chef CLI version: 3.0.11
Test Kitchen version: 2.5.3
Cookstyle version: 6.12.6

Gem: kitchen-ec2 (3.7.1)

## Environment

Running kitchen command from aws windows workspaces machine. Running powershell and kitchen converge rhel-7.
snippet of my kitchen.ec2.yml file. Environment variable KITCHEN_LOCAL_YAML=kitchen.ec2.yml
```yaml
---
driver:
  name: ec2
  region: us-east-1
  subnet_id: subnet-example
  instance_type: t3a.medium
  retryable_tries: 120
platforms:
  - name: rhel-7
```

## Scenario

Converge on latest stable version of RHEL 7. Instead of getting a RHEL 7.8 machine I'm getting a RHEL 7.9 beta ami.

## Steps to Reproduce

create kitchen.yml with ec2 driver and platform name rhel-7 then run converge

## Expected Result

`cat /etc/redhat-release` to show that it's on a rhel 7.8 

## Actual Result

`cat /etc/redhat-release` will show that it's on a rhel 7.9 beta

### PR DESCRIPTION
**Pull request by clintoncwolfe**
# Description

When searching for RHEL AMIs, this change alters the search sort so that Beta AMIs are sorted after non-Beta (GA) AMIs. This has the effect of making it so that searches for `rhel-7` will return RHEL 7.8 rather than RHEL 7.9 Beta, which is the expected behavior. 

To obtain RHEL 7.9, search explicitly for `rhel-7.9` - that will cause all search results to be Beta, in which case this search sort change will have no effect.

Also includes a drive-by Chefstyle update for removing the encoding comments, on a separate commit.

## Issues Resolved

Fixes #505

Closes chef/chef-workstation#1410

## Check List

- [x] All tests pass. See TESTING.md for details.
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable.

### CODE REVIEW

File: lib/kitchen/driver/aws/standard_platform/rhel.rb [hunk 1]
```diff
@@ -50,6 +50,13 @@ def self.from_image(driver, image)
               new(driver, "rhel", (Regexp.last_match || [])[1], image.architecture)
             end
           end
+
+          def sort_by_version(images)
+            # First do a normal version sort
+            super(images)
+            # Now sort again, shunning Beta releases.
+            prefer(images) { |image| !image.name.match(/_Beta-/i) }
```
Comment (clintoncwolfe) [inline lib/kitchen/driver/aws/standard_platform/rhel.rb:58]: "RHEL-7.9_HVM_BETA-20200422-x86_64-0-Hourly2-GP2"
"RHEL-7.8_HVM_GA-20200225-x86_64-1-Hourly2-GP2"
"RHEL-7.4_HVM_Beta-20170518-x86_64-1-Hourly2-GP2"
Are some examples of the strings to match.
